apiVersion: v1
kind: Pod
metadata:
  name: springboot-app
spec:
  containers:
    - name: springboot-container
      image: springboot-app:latest  # Replace with your actual image name
      volumeMounts:
        - name: config-volume
          mountPath: /config/application.properties  # Where the file will appear in the container
          subPath: application.properties
      env:
        - name: SPRING_CONFIG_LOCATION
          value: "file:/config/application.properties"  # Directs Spring Boot to use this file
  volumes:
    - name: config-volume
      hostPath:
        path: /path/to/application.properties  # Path to your properties file on the host
        type: File
